package rain.api.gfx

import org.lwjgl.vulkan.VK10.*

enum class BlendMode(value: Int) {
    BLEND_FACTOR_ZERO(VK_BLEND_FACTOR_ZERO),
    BLEND_FACTOR_ONE(VK_BLEND_FACTOR_ONE),
    BLEND_FACTOR_SRC_COLOR(VK_BLEND_FACTOR_SRC_COLOR),
    BLEND_FACTOR_ONE_MINUS_SRC_COLOR(VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR),
    BLEND_FACTOR_DST_COLOR(VK_BLEND_FACTOR_DST_COLOR),
    BLEND_FACTOR_ONE_MINUS_DST_COLOR(VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR),
    BLEND_FACTOR_SRC_ALPHA(VK_BLEND_FACTOR_SRC_ALPHA),
    BLEND_FACTOR_ONE_MINUS_SRC_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA),
    BLEND_FACTOR_DST_ALPHA(VK_BLEND_FACTOR_DST_ALPHA),
    BLEND_FACTOR_ONE_MINUS_DST_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA),
    BLEND_FACTOR_CONSTANT_COLOR(VK_BLEND_FACTOR_CONSTANT_COLOR),
    BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR(VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR),
    BLEND_FACTOR_CONSTANT_ALPHA(VK_BLEND_FACTOR_CONSTANT_ALPHA),
    BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA),
    BLEND_FACTOR_SRC_ALPHA_SATURATE(VK_BLEND_FACTOR_SRC_ALPHA_SATURATE),
    BLEND_FACTOR_SRC1_COLOR(VK_BLEND_FACTOR_SRC1_COLOR),
    BLEND_FACTOR_ONE_MINUS_SRC1_COLOR(VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR),
    BLEND_FACTOR_SRC1_ALPHA(VK_BLEND_FACTOR_SRC1_ALPHA),
    BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA);

    val value = value
}
